on: [workflow_dispatch]
name: DemoEnvironment PROD Deployment
jobs:
  deploy-prod:
    runs-on: ubuntu-latest
    steps:
      # Checkout code
    - uses: actions/checkout@main

      # Log into Azure
    - uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

      # Deploy Bicep file
    - name: deploy
      uses: azure/arm-deploy@v1
      with:
        scope: subscription
        subscriptionId: ${{ secrets.AZURE_SUBSCRIPTION }}
        deploymentName: 'CI-DemoEnvironment-prod'
        region: 'germanywestcentral'
        template: ./02_Modules/DemoEnvironment.bicep
        parameters: ./02_Modules/DemoEnvironment-prod.bicepparam
        failOnStdErr: false
